name: Fetch TV List Every 2 Hours

on:
  schedule:
  - cron: '0 */2 * * *'     # 每两小时一次
  workflow_dispatch:       # 可手动触发

jobs:
  fetch_tvlist:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v3

      - name: 创建 tv 目录（如果不存在）
        run: mkdir -p tv

      - name: 下载 tvlist.txt 并保存
        run: curl -s https://render-node-demo-6ijt.onrender.com/tvlist.txt -o docs/tv/tvlist.txt

      - name: 提交更新（如果有变化）
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add docs/tv/tvlist.txt

          if git diff --cached --quiet; then
            echo "文件无变化，跳过提交"
          else
            git commit -m "自动更新 tvlist.txt: $(date -u '+%Y-%m-%d %H:%M:%S')"
            git pull --rebase origin main
            git push
          fi
